project_id = "jpndzcsqfuumdrcyjfxl"

[functions.generate-viral-content]
verify_jwt = false

[functions.generate-thumbnail]
verify_jwt = false

[functions.process-scheduled-posts]
verify_jwt = false

[functions.tiktok-oauth]
verify_jwt = true

[functions.tiktok-oauth-callback]
verify_jwt = false

[functions.tiktok-verification]
verify_jwt = false
